from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from functools import lru_cache

from app.core import get_settings
from app.services.gemini import gemini_generate_content, gemini_is_enabled
from app.services.text_cleaner import clean_article_text

logger = logging.getLogger(__name__)

SUMMARY_LINE_COUNT = 3
MAX_LINE_LENGTH = 120
MIN_SENTENCE_CHARACTERS = 24
MIN_CLAUSE_CHARACTERS = 20

_SENTENCE_SPLIT_PATTERN = re.compile(r"(?<=[.!?])\s+|\n+")
_GENERATED_LINE_SPLIT_PATTERN = re.compile(r"(?<=[.!?])\s+")
_CLAUSE_SPLIT_PATTERN = re.compile(r";|:| -- | - |, (?=(?:but|while|as|after|before|despite)\b)", re.IGNORECASE)
_TOKEN_PATTERN = re.compile(r"[A-Za-z]{2,}|\d+(?:\.\d+)?%?")
_NUMERIC_TOKEN_PATTERN = re.compile(r"\$?\d[\d,]*(?:\.\d+)?%?")
_MULTI_SPACE_PATTERN = re.compile(r"\s+")
_GENERIC_PREFIX_PATTERN = re.compile(
    r"^(?:the article|the report|this article|in the article)\s+(?:says|reports|notes|highlights)\s+that\s+",
    re.IGNORECASE,
)

_STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "has",
    "in",
    "into",
    "is",
    "it",
    "of",
    "on",
    "or",
    "that",
    "the",
    "their",
    "to",
    "was",
    "were",
    "with",
}

_FINANCIAL_KEYWORDS = {
    "acquisition",
    "analyst",
    "bank",
    "bond",
    "buyback",
    "cash",
    "cost",
    "credit",
    "debt",
    "dividend",
    "earnings",
    "estimate",
    "forecast",
    "guidance",
    "inflation",
    "loss",
    "margin",
    "market",
    "merger",
    "outlook",
    "profit",
    "quarter",
    "rate",
    "revenue",
    "risk",
    "sales",
    "shares",
    "stock",
    "tariff",
    "valuation",
}


@dataclass(frozen=True, slots=True)
class _CandidateLine:
    text: str
    score: float
    position: int
    source_position: int
    kind: str


def summarize_to_three_lines(title: str, article_text: str) -> list[str]:
    """Return exactly three summary lines generated by Gemini."""
    cleaned_text = clean_article_text(article_text)
    if not cleaned_text:
        return ["", "", ""]

    gemini_input = _prepare_summary_input(cleaned_text)
    gemini_summary = _summarize_with_gemini(title=title, article_text=gemini_input)
    if gemini_summary is None:
        logger.warning("Gemini summary unavailable; returning empty summary lines.")
        return ["", "", ""]
    return gemini_summary


def _summarize_with_gemini(*, title: str, article_text: str) -> list[str] | None:
    settings = get_settings()
    if not settings.enable_gemini_summary or not gemini_is_enabled():
        return None

    if len(article_text) > settings.gemini_summary_hard_char_limit:
        logger.info(
            "Gemini summary skipped for oversized article.",
            extra={"article_text_length": len(article_text)},
        )
        return None
    try:
        content = _cached_summary_completion(
            settings.gemini_api_base_url,
            settings.gemini_summary_model,
            title,
            article_text,
        )
    except Exception:
        logger.exception("Gemini summary generation failed.")
        return None

    lines = _parse_summary_lines(content)
    if len(lines) != SUMMARY_LINE_COUNT or not all(line.strip() for line in lines):
        logger.warning("Gemini summary generation returned unusable output.")
        return None
    if not _summary_preserves_numeric_facts(lines, title=title, article_text=article_text):
        logger.warning("Gemini summary generation introduced unsupported numeric facts.")
        return None
    return lines


def _parse_summary_lines(content: str) -> list[str]:
    lines: list[str] = []
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        line = re.sub(r"^(?:[-*•]\s*|\d+[.)]\s*)", "", line).strip()
        if not line:
            continue

        line_fragments = _split_generated_line(line)
        for fragment in line_fragments:
            normalized = _normalize_generated_line(fragment)
            if normalized:
                lines.append(normalized)
            if len(lines) == SUMMARY_LINE_COUNT:
                break
        if len(lines) == SUMMARY_LINE_COUNT:
            break
    return lines


def _split_generated_line(line: str) -> list[str]:
    fragments = [fragment.strip() for fragment in _GENERATED_LINE_SPLIT_PATTERN.split(line)]
    return [fragment for fragment in fragments if fragment]


def _normalize_generated_line(line: str) -> str:
    return _normalize_text(line).removesuffix("...").strip()


def _summary_preserves_numeric_facts(lines: list[str], *, title: str, article_text: str) -> bool:
    source_numeric_tokens = _extract_numeric_tokens(f"{title} {article_text}")
    if not source_numeric_tokens:
        return True

    summary_numeric_tokens = _extract_numeric_tokens(" ".join(lines))
    return summary_numeric_tokens.issubset(source_numeric_tokens)


def _extract_numeric_tokens(text: str) -> set[str]:
    return {match.group(0) for match in _NUMERIC_TOKEN_PATTERN.finditer(text)}


@lru_cache(maxsize=256)
def _cached_summary_completion(base_url: str, model: str, title: str, article_text: str) -> str:
    del base_url
    return gemini_generate_content(
        model=model,
        system_prompt=(
            "You are a Korean financial news editor. "
            "Rewrite the article into exactly 3 Korean summary lines. "
            "Use neutral financial news style and declarative '-했다' sentences. "
            "Write exactly one complete sentence per line. "
            "Keep each line concise, natural, and self-contained. "
            "Keep numbers, percentages, dates, currencies, ticker symbols, and factual details unchanged. "
            "Never invent or infer missing details. "
            "Do not repeat the title. "
            "Do not use bullets, numbering, quotes, commentary, or ellipses. "
            "Ignore tables, reconciliation labels, datelines, boilerplate, and footer text. "
            "Prefer concrete business facts such as revenue, guidance, margins, demand, dividends, and outlook. "
            "Return only 3 plain Korean lines."
        ),
        user_prompt=f"Title: {title}\nArticle:\n{article_text}",
        temperature=0.0,
        request_label="summary_generation",
    )


def _prepare_summary_input(text: str) -> str:
    settings = get_settings()
    normalized = _normalize_text(text)
    if len(normalized) <= settings.gemini_summary_soft_char_limit:
        return normalized

    sentences = _extract_sentences(normalized)
    if not sentences:
        return normalized[: settings.gemini_summary_soft_char_limit]

    prepared = _build_balanced_summary_context(
        sentences,
        char_limit=settings.gemini_summary_soft_char_limit,
    )
    return prepared or normalized[: settings.gemini_summary_soft_char_limit]


def _build_balanced_summary_context(sentences: list[str], *, char_limit: int) -> str:
    if not sentences:
        return ""

    selection_order = _build_summary_sentence_selection_order(len(sentences))
    selected_indices: list[int] = []
    current_length = 0

    for index in selection_order:
        if index in selected_indices:
            continue
        sentence = sentences[index]
        sentence_length = len(sentence) + (2 if selected_indices else 0)
        if current_length + sentence_length > char_limit:
            continue
        selected_indices.append(index)
        current_length += sentence_length

    if not selected_indices:
        return sentences[0][:char_limit]

    selected_indices.sort()
    return " ".join(sentences[index] for index in selected_indices).strip()


def _build_summary_sentence_selection_order(sentence_count: int) -> list[int]:
    if sentence_count <= 0:
        return []

    order: list[int] = []
    seen: set[int] = set()

    def _append(index: int) -> None:
        if 0 <= index < sentence_count and index not in seen:
            seen.add(index)
            order.append(index)

    midpoint = sentence_count // 2
    max_offset = max(midpoint, sentence_count - midpoint - 1)
    for offset in range(max_offset + 1):
        _append(offset)
        if offset > 0:
            _append(midpoint - offset)
        _append(midpoint + offset)
        _append(sentence_count - 1 - offset)

    return order


def _extract_sentences(text: str) -> list[str]:
    protected_text = _protect_abbreviations(text)
    parts = _SENTENCE_SPLIT_PATTERN.split(protected_text)
    sentences: list[str] = []
    for part in parts:
        sentence = _normalize_text(_restore_abbreviations(part))
        if len(sentence) < MIN_SENTENCE_CHARACTERS:
            continue
        if sentence not in sentences:
            sentences.append(sentence)
    return sentences


def _build_candidates(sentences: list[str], title_tokens: set[str]) -> list[_CandidateLine]:
    candidates: list[_CandidateLine] = []
    for index, sentence in enumerate(sentences):
        score = _score_sentence(sentence, index, title_tokens)
        candidates.append(
            _CandidateLine(
                text=sentence,
                score=score + 0.3,
                position=index,
                source_position=index,
                kind="sentence",
            )
        )

        for clause in _extract_clauses(sentence):
            clause_score = score - 0.35
            candidates.append(
                _CandidateLine(
                    text=clause,
                    score=clause_score,
                    position=index,
                    source_position=index,
                    kind="clause",
                )
            )

    return candidates


def _score_sentence(sentence: str, index: int, title_tokens: set[str]) -> float:
    tokens = _tokenize(sentence)
    overlap = len(tokens & title_tokens)
    finance_hits = len(tokens & _FINANCIAL_KEYWORDS)
    numeric_hits = sentence.count("%") + sentence.count("$")
    position_bonus = max(0.0, 2.5 - (index * 0.25))
    length_bonus = min(len(tokens) / 12, 1.5)

    score = position_bonus + (overlap * 1.7) + (finance_hits * 0.8) + (numeric_hits * 0.5) + length_bonus

    if _looks_like_title_echo(sentence, title_tokens):
        score -= 1.5
    if _is_generic_sentence(sentence):
        score -= 1.0

    return score


def _extract_clauses(sentence: str) -> list[str]:
    clauses: list[str] = []
    for part in _CLAUSE_SPLIT_PATTERN.split(sentence):
        clause = _normalize_text(part)
        if len(clause) >= MIN_CLAUSE_CHARACTERS and clause != sentence and clause not in clauses:
            clauses.append(clause)
    return clauses


def _select_distinct_candidates(candidates: list[_CandidateLine]) -> list[_CandidateLine]:
    ranked = sorted(
        candidates,
        key=lambda item: (-item.score, item.position, item.kind != "sentence", len(item.text)),
    )
    selected: list[_CandidateLine] = []
    used_sources: set[int] = set()

    for candidate in ranked:
        if candidate.source_position in used_sources:
            continue
        if _is_too_similar_to_any(candidate.text, [item.text for item in selected]):
            continue
        selected.append(candidate)
        used_sources.add(candidate.source_position)
        if len(selected) >= SUMMARY_LINE_COUNT:
            break

    if len(selected) < SUMMARY_LINE_COUNT:
        for candidate in ranked:
            if candidate in selected:
                continue
            if _is_too_similar_to_any(candidate.text, [item.text for item in selected]):
                continue
            selected.append(candidate)
            if len(selected) >= SUMMARY_LINE_COUNT:
                break

    return sorted(selected, key=lambda item: item.position)


def _tokenize(text: str) -> set[str]:
    tokens = {match.group(0).lower() for match in _TOKEN_PATTERN.finditer(text)}
    return {token for token in tokens if token not in _STOPWORDS}


def _normalize_text(text: str) -> str:
    text = _MULTI_SPACE_PATTERN.sub(" ", text).strip(" \t\n-")
    text = _GENERIC_PREFIX_PATTERN.sub("", text)
    return text.strip()


def _looks_like_title_echo(sentence: str, title_tokens: set[str]) -> bool:
    sentence_tokens = _tokenize(sentence)
    if not sentence_tokens or not title_tokens:
        return False
    overlap_ratio = len(sentence_tokens & title_tokens) / max(len(title_tokens), 1)
    return overlap_ratio >= 0.8


def _is_generic_sentence(sentence: str) -> bool:
    lowered = sentence.lower()
    return lowered.startswith(("the article ", "the report ", "this article "))


def _is_too_similar_to_any(candidate: str, existing_lines: list[str]) -> bool:
    candidate_tokens = _tokenize(candidate)
    if not candidate_tokens:
        return True

    for line in existing_lines:
        line_tokens = _tokenize(line)
        if not line_tokens:
            continue
        overlap = len(candidate_tokens & line_tokens) / max(len(candidate_tokens | line_tokens), 1)
        if overlap >= 0.7:
            return True
    return False


def _truncate_for_card(text: str) -> str:
    normalized = _normalize_text(text)
    if len(normalized) <= MAX_LINE_LENGTH:
        return normalized

    truncated = normalized[:MAX_LINE_LENGTH].rsplit(" ", 1)[0].rstrip(",;:-")
    if not truncated:
        truncated = normalized[:MAX_LINE_LENGTH].rstrip(",;:-")
    return f"{truncated}..."


def _protect_abbreviations(text: str) -> str:
    return re.sub(r"\b(?:[A-Z]\.){2,}", lambda match: match.group(0).replace(".", "<prd>"), text)


def _restore_abbreviations(text: str) -> str:
    return text.replace("<prd>", ".")
