from __future__ import annotations

import logging
import re
from functools import lru_cache

from app.core import get_settings
from app.services.gemini import gemini_generate_content, gemini_is_enabled
from app.services.text_cleaner import clean_article_text

logger = logging.getLogger(__name__)

SUMMARY_LINE_COUNT = 3
MIN_SENTENCE_CHARACTERS = 24

_SENTENCE_SPLIT_PATTERN = re.compile(r"(?<=[.!?])\s+|\n+")
_GENERATED_LINE_SPLIT_PATTERN = re.compile(r"(?<=[.!?])\s+")
_NUMERIC_TOKEN_PATTERN = re.compile(r"\$?\d[\d,]*(?:\.\d+)?%?")
_MULTI_SPACE_PATTERN = re.compile(r"\s+")
_GENERIC_PREFIX_PATTERN = re.compile(
    r"^(?:the article|the report|this article|in the article)\s+(?:says|reports|notes|highlights)\s+that\s+",
    re.IGNORECASE,
)


def summarize_to_three_lines(title: str, article_text: str) -> list[str]:
    """Return exactly three summary lines generated by Gemini."""
    cleaned_text = clean_article_text(article_text)
    if not cleaned_text:
        return ["", "", ""]

    gemini_input = _prepare_summary_input(cleaned_text)
    gemini_summary = _summarize_with_gemini(title=title, article_text=gemini_input)
    if gemini_summary is None:
        logger.warning("Gemini summary unavailable; returning empty summary lines.")
        return ["", "", ""]
    return gemini_summary


def _summarize_with_gemini(*, title: str, article_text: str) -> list[str] | None:
    settings = get_settings()
    if not gemini_is_enabled():
        return None

    if len(article_text) > settings.gemini_summary_hard_char_limit:
        logger.info(
            "Gemini summary skipped for oversized article.",
            extra={"article_text_length": len(article_text)},
        )
        return None
    try:
        content = _cached_summary_completion(
            settings.gemini_api_base_url,
            settings.gemini_summary_model,
            title,
            article_text,
        )
    except Exception:
        logger.exception("Gemini summary generation failed.")
        return None

    lines = _parse_summary_lines(content)
    if len(lines) != SUMMARY_LINE_COUNT or not all(line.strip() for line in lines):
        logger.warning("Gemini summary generation returned unusable output.")
        return None
    if not _summary_preserves_numeric_facts(lines, title=title, article_text=article_text):
        logger.warning("Gemini summary generation introduced unsupported numeric facts.")
        return None
    return lines


def _parse_summary_lines(content: str) -> list[str]:
    lines: list[str] = []
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        line = re.sub(r"^(?:[-*•]\s*|\d+[.)]\s*)", "", line).strip()
        if not line:
            continue

        line_fragments = _split_generated_line(line)
        for fragment in line_fragments:
            normalized = _normalize_generated_line(fragment)
            if normalized:
                lines.append(normalized)
            if len(lines) == SUMMARY_LINE_COUNT:
                break
        if len(lines) == SUMMARY_LINE_COUNT:
            break
    return lines


def _split_generated_line(line: str) -> list[str]:
    fragments = [fragment.strip() for fragment in _GENERATED_LINE_SPLIT_PATTERN.split(line)]
    return [fragment for fragment in fragments if fragment]


def _normalize_generated_line(line: str) -> str:
    return _normalize_text(line).removesuffix("...").strip()


def _summary_preserves_numeric_facts(lines: list[str], *, title: str, article_text: str) -> bool:
    source_numeric_tokens = _extract_numeric_tokens(f"{title} {article_text}")
    if not source_numeric_tokens:
        return True

    summary_numeric_tokens = _extract_numeric_tokens(" ".join(lines))
    return summary_numeric_tokens.issubset(source_numeric_tokens)


def _extract_numeric_tokens(text: str) -> set[str]:
    return {_normalize_numeric_token(match.group(0)) for match in _NUMERIC_TOKEN_PATTERN.finditer(text)}


def _normalize_numeric_token(token: str) -> str:
    normalized = token.strip().replace(",", "")
    if normalized.startswith("$"):
        return f"${_normalize_plain_number(normalized[1:])}"
    return _normalize_plain_number(normalized)


def _normalize_plain_number(text: str) -> str:
    suffix = ""
    if text.endswith("%"):
        suffix = "%"
        text = text[:-1]
    if "." in text and text.replace(".", "", 1).isdigit():
        text = text.rstrip("0").rstrip(".")
    return f"{text}{suffix}"


@lru_cache(maxsize=256)
def _cached_summary_completion(base_url: str, model: str, title: str, article_text: str) -> str:
    del base_url
    return gemini_generate_content(
        model=model,
        system_prompt=(
            "You are a Korean financial news editor. "
            "Produce exactly 3 Korean summary lines from the article. "
            "Each line must be one complete sentence in neutral financial 기사체. "
            "Use concise declarative endings such as '-했다' or '-밝혔다'. "
            "Preserve numbers, percentages, dates, currencies, ticker symbols, and factual entities exactly. "
            "Do not invent, infer, exaggerate, or add unstated causes. "
            "Do not repeat the title. "
            "Do not output bullets, numbering, quotes, commentary, or metadata. "
            "Ignore table captions, reconciliation headers, datelines, and footer boilerplate. "
            "Prioritize concrete business facts such as 실적, 가이던스, 수요, 마진, 배당, 전망. "
            "Return only 3 plain Korean lines."
        ),
        user_prompt=f"Title: {title}\nArticle:\n{article_text}",
        temperature=0.0,
        request_label="summary_generation",
    )


def _prepare_summary_input(text: str) -> str:
    settings = get_settings()
    normalized = _normalize_text(text)
    if len(normalized) <= settings.gemini_summary_soft_char_limit:
        return normalized

    sentences = _extract_sentences(normalized)
    if not sentences:
        return normalized[: settings.gemini_summary_soft_char_limit]

    prepared = _build_balanced_summary_context(
        sentences,
        char_limit=settings.gemini_summary_soft_char_limit,
    )
    return prepared or normalized[: settings.gemini_summary_soft_char_limit]


def _build_balanced_summary_context(sentences: list[str], *, char_limit: int) -> str:
    if not sentences:
        return ""

    selection_order = _build_summary_sentence_selection_order(len(sentences))
    selected_indices: list[int] = []
    current_length = 0

    for index in selection_order:
        if index in selected_indices:
            continue
        sentence = sentences[index]
        sentence_length = len(sentence) + (2 if selected_indices else 0)
        if current_length + sentence_length > char_limit:
            continue
        selected_indices.append(index)
        current_length += sentence_length

    if not selected_indices:
        return sentences[0][:char_limit]

    selected_indices.sort()
    return " ".join(sentences[index] for index in selected_indices).strip()


def _build_summary_sentence_selection_order(sentence_count: int) -> list[int]:
    if sentence_count <= 0:
        return []

    order: list[int] = []
    seen: set[int] = set()

    def _append(index: int) -> None:
        if 0 <= index < sentence_count and index not in seen:
            seen.add(index)
            order.append(index)

    midpoint = sentence_count // 2
    max_offset = max(midpoint, sentence_count - midpoint - 1)
    for offset in range(max_offset + 1):
        _append(offset)
        if offset > 0:
            _append(midpoint - offset)
        _append(midpoint + offset)
        _append(sentence_count - 1 - offset)

    return order


def _extract_sentences(text: str) -> list[str]:
    protected_text = _protect_abbreviations(text)
    parts = _SENTENCE_SPLIT_PATTERN.split(protected_text)
    sentences: list[str] = []
    for part in parts:
        sentence = _normalize_text(_restore_abbreviations(part))
        if len(sentence) < MIN_SENTENCE_CHARACTERS:
            continue
        if sentence not in sentences:
            sentences.append(sentence)
    return sentences


def _normalize_text(text: str) -> str:
    text = _MULTI_SPACE_PATTERN.sub(" ", text).strip(" \t\n-")
    text = _GENERIC_PREFIX_PATTERN.sub("", text)
    return text.strip()


def _protect_abbreviations(text: str) -> str:
    return re.sub(r"\b(?:[A-Z]\.){2,}", lambda match: match.group(0).replace(".", "<prd>"), text)


def _restore_abbreviations(text: str) -> str:
    return text.replace("<prd>", ".")
