from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import requests


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate release/canary readiness using suite summary and operational stats."
        )
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8000",
        help="Base URL of the GenAI service.",
    )
    parser.add_argument(
        "--suite-summary",
        required=True,
        help="Path to suite_summary.json generated by scripts/run_smoke_suite.py.",
    )
    parser.add_argument(
        "--min-success-ratio",
        type=float,
        default=0.90,
        help="Minimum success ratio required to pass gate.",
    )
    parser.add_argument(
        "--max-fatal-ratio",
        type=float,
        default=0.02,
        help="Maximum fatal failure ratio allowed.",
    )
    parser.add_argument(
        "--max-timeout-ratio",
        type=float,
        default=0.05,
        help="Maximum timeout failure ratio allowed from /operations/stats.",
    )
    parser.add_argument(
        "--max-summarize-failed-ratio",
        type=float,
        default=0.15,
        help="Maximum summarize_failed ratio allowed from /operations/stats.",
    )
    parser.add_argument(
        "--max-rate-limited-ratio",
        type=float,
        default=0.20,
        help="Maximum Gemini rate-limited ratio allowed from /operations/stats.",
    )
    parser.add_argument(
        "--min-cleaned-preservation-ratio",
        type=float,
        default=0.30,
        help="Minimum average cleaned/raw preservation ratio.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=20.0,
        help="HTTP timeout for operational stats request.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    suite_summary = _load_suite_summary(Path(args.suite_summary))
    ops_stats = _fetch_operational_stats(base_url=args.base_url, timeout=args.timeout)

    total_runs = int(suite_summary.get("total_runs", 0))
    total_success = int(suite_summary.get("total_success", 0))
    total_fatal = int(suite_summary.get("total_fatal_failure", 0))
    success_ratio = (total_success / total_runs) if total_runs else 0.0
    fatal_ratio = (total_fatal / total_runs) if total_runs else 1.0

    summarize_failed_ratio = float(ops_stats.get("summarize_failed_ratio", 0.0))
    timeout_ratio = float(ops_stats.get("timeout_failure_ratio", 0.0))
    rate_limited_ratio = float(ops_stats.get("gemini_rate_limited_ratio", 0.0))
    avg_preservation = ops_stats.get("average_cleaned_to_raw_ratio")
    avg_preservation = float(avg_preservation) if avg_preservation is not None else 1.0

    checks = [
        (
            "success_ratio",
            success_ratio,
            success_ratio >= args.min_success_ratio,
            f">= {args.min_success_ratio:.2f}",
        ),
        (
            "fatal_ratio",
            fatal_ratio,
            fatal_ratio <= args.max_fatal_ratio,
            f"<= {args.max_fatal_ratio:.2f}",
        ),
        (
            "timeout_ratio",
            timeout_ratio,
            timeout_ratio <= args.max_timeout_ratio,
            f"<= {args.max_timeout_ratio:.2f}",
        ),
        (
            "summarize_failed_ratio",
            summarize_failed_ratio,
            summarize_failed_ratio <= args.max_summarize_failed_ratio,
            f"<= {args.max_summarize_failed_ratio:.2f}",
        ),
        (
            "gemini_rate_limited_ratio",
            rate_limited_ratio,
            rate_limited_ratio <= args.max_rate_limited_ratio,
            f"<= {args.max_rate_limited_ratio:.2f}",
        ),
        (
            "average_cleaned_to_raw_ratio",
            avg_preservation,
            avg_preservation >= args.min_cleaned_preservation_ratio,
            f">= {args.min_cleaned_preservation_ratio:.2f}",
        ),
    ]

    result = {
        "suite_summary_path": str(Path(args.suite_summary).resolve()),
        "total_runs": total_runs,
        "total_success": total_success,
        "total_fatal_failure": total_fatal,
        "checks": [
            {
                "name": name,
                "value": round(value, 4),
                "expected": expected,
                "pass": passed,
            }
            for name, value, passed, expected in checks
        ],
    }
    result["pass"] = all(item["pass"] for item in result["checks"])

    print(json.dumps(result, ensure_ascii=True, indent=2))
    return 0 if result["pass"] else 2


def _load_suite_summary(path: Path) -> dict[str, object]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Suite summary must be a JSON object.")
    return payload


def _fetch_operational_stats(*, base_url: str, timeout: float) -> dict[str, object]:
    response = requests.get(
        f"{base_url.rstrip('/')}/api/v1/operations/stats",
        timeout=timeout,
    )
    response.raise_for_status()
    payload = response.json()
    if not isinstance(payload, dict):
        raise RuntimeError("Operational stats response was not a JSON object.")
    return payload


if __name__ == "__main__":
    raise SystemExit(main())

